### ISSUE TITLE
Add some basic prometheus metrics

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/faucet#32]
We should have alertable metrics such as:

- current faucet wallet balance
- number of outstanding requests in the queue
- time to fulfill each faucet request

We will also need to add a service monitor to the helm chart template for prometheus to auto-discover these metrics.

**Comment by BossHog1313** [comment]
After discussing a bit with Brandon, here's an initial scope for faucet metrics (the faucet is something we deploy alongside fuel-core in our test networks to issue fake coins that people can spend):

- Faucet [webapp](https://faucet-beta3.swayswap.io/).
- Fuel-core [url](https://github.com/FuelLabs/fuel-core/blob/master/crates/metrics/src/core_metrics.rs).

**Sample code**:

[Minimal metrics](https://github.com/FuelLabs/fuel-core/blob/master/crates/metrics/src/core_metrics.rs):
```
use lazy_static::lazy_static;
use prometheus_client::{
    metrics::{
        counter::Counter,
        histogram::Histogram,
...
```
[Metrics to HTTP response](https://github.com/FuelLabs/fuel-core/blob/master/crates/metrics/src/service.rs):
```
use crate::{
    p2p_metrics::P2P_METRICS,
    txpool_metrics::TXPOOL_METRICS,
};
use axum::{
    body::Body,
    response::{
        IntoResponse,
        Response,
    },
};
use prometheus_client::encoding::text::encode;
use std::vec;
...
```
[Bind router to metrics function](https://github.com/FuelLabs/faucet/blob/master/src/lib.rs#L79):
```
.route("/health", get(health))
...
```
[Router entry point](https://github.com/FuelLabs/faucet/blob/master/src/lib.rs#L79):
```
let app = Router::new()
...
```

**Comment by BossHog1313** [comment]
@Voxelot Hello sir! Where might I find information/documentation on the faucet-related metrics we want to add to our core metrics Rust codebase? Thanks!

**Comment by BossHog1313** [comment]
I've written a new metrics collection crate that offers an endpoint (/metrics) to access a number of Prometheus metrics. This is a first pass; I do not yet understand our fuel-core service architecture, and how precisely we access different metric groups (eg. database). Changes will likely be necessary, but I'm beginning to understand Rust and how some things function.

**Comment by BossHog1313** [comment]
I now have a process metrics crate that is syntactically correct, and integrates with faucet. Need to do a bit more to ensure these metrics are properly collected. I also must understand how we make them available for faucet.

**Comment by Voxelot** [comment]
The system / process metrics could be useful, but may be redundant with what's already being ingested by kubernetes: https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/

I'd recommend checking out the grafana dashboard editor to see which ones are already collected from a system level.

As far as metrics to collect, I put some in the original issue description:

- current faucet wallet balance
- number of outstanding requests in the queue
- time to fulfill each faucet request

These are more application specific, and would allow us to measure faucet demand as well as monitor the amount of funds the faucet has remaining.

How to collect these app metrics?

## Current faucet wallet balance

Currently the faucet balance is only checked on startup:
<img width="689" alt="Screen Shot 2023-03-29 at 6 37 08 PM" src="https://user-images.githubusercontent.com/794823/228705525-cc0f7d4e-dc77-4089-b60c-06c0aa012cac.png">

We could add an async interval task that checks the balance periodically and updates a prometheus gauge.

e.g. 

```rust
    tokio::spawn(async || {
        let mut interval = tokio::time::interval(Duration::from_secs(30));
        for tick in interval.tick().await {
            let balance = wallet
                .get_coins(service_config.dispense_asset_id)
                .await
                .expect("Failed to fetch initial balance from fuel core")
                .into_iter()
                .filter_map(|coin| match coin.status {
                    fuels_types::coin::CoinStatus::Unspent => Some(coin.amount),
                    _ => None,
                })
                .sum::<u64>();
            // TODO: update prometheus gauge with balance
        }
    });
```

## Number of outstanding requests in the queue

The faucet currently doesn't support concurrent requests and queues them via axum's route configurations. 

<img width="656" alt="Screen Shot 2023-03-29 at 6 54 41 PM" src="https://user-images.githubusercontent.com/794823/228707934-54217103-96b6-40bd-b819-35721e135250.png">

It may be difficult to extract this information from the webserver middleware, and I'd say that this metric is more optional.

## time to fulfill each faucet request

It would be good to have more data about how long users are waiting to get their tokens from the faucet, as well as how many faucet requests we are processing. Using a single prometheus [histogram](https://prometheus.io/docs/concepts/metric_types/) metric, this give us both.

The timing could be done within the `dispense_tokens` method, which is the handler that processes token disbursements. Each timing measurement should be added to the prometheus histogram metric.

**Comment by BossHog1313** [comment]
It's been decided to include only those metrics defined in the initial task description, so we'll go that route.

**Comment by rfuelsh** [comment]
old
