### ISSUE TITLE
Faucet believes the wallet extension has already received funds today

### ISSUE THREAD

**Issue by HoTandy** [FuelLabs/faucet#65]
Moved from https://github.com/FuelLabs/fuels-wallet/issues/1114 at the request of @luizstacio 

### What version of Wallet are you using?

0.15.2

### What is happening?

I used the bridge to to withdraw assets from the fuel network to a Sepolia ETH account that I've setup in Metamask.
Afterwards, I wanted to re-fund my Fuel wallet from the Faucet, but when I attempt to do this, I get a message stating:

`Account has already received assets today`

![image](https://github.com/FuelLabs/fuels-wallet/assets/114662397/3a4f0389-c653-4db6-a1d3-87e2cd36ed8a)

This is not the case though, although there has been a withdrawal activity.

![image](https://github.com/FuelLabs/fuels-wallet/assets/114662397/34f320b1-0743-4b32-ab02-90bd8a33439e)

Could it be that the Faucet thinks the withdrawal activity is a deposit activity?  Is this a bug?

### steps to reproduce

1. Use the bridge to withdraw funds to an external (Sepolia ETH) wallet https://app.fuel.network/portal/bridge?from=fuel&to=eth
2. Use the Faucet to add funds back into the Fuel wallet. https://faucet-beta-5.fuel.network/

Then we see the message that this is not possible.

### How it should behave?

It should be possible to fund the wallet from the faucet.

### What os are you seeing the problem on?

Mac/Apple Desktop

### What browser?

Chrome

### What is your browser version?

122.0.6261.69 (Official Build) (x86_64)

**Comment by HoTandy** [comment]
The following conversations are relevant on Slack:

https://hotfuel.slack.com/archives/C06JHN4SB0X/p1708962186219849

https://fuellabs.slack.com/archives/C064X8Z9YSY/p1710416244576319?thread_ts=1710414348.571999&cid=C064X8Z9YSY

**Comment by HoTandy** [comment]
This issue has been worked on recently and might now be fixed.

**Comment by xgreenx** [comment]
It is fixed with https://github.com/FuelLabs/faucet/releases/tag/v0.6.5
